### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by grassator** [grassator/mass#15]
This is issue will be used to track progress to being able to support Linux both as a cross-compilation target from Windows and having a Linux build of the compiler. Relevant issues will be referenced in the list below.

* [x] [Support building the compiler on linux](https://github.com/grassator/mass/issues/14)
* [x] [Static if/else](https://github.com/grassator/mass/issues/7) For a single program to be runnable on multiple system, we will need some form of static dispatch based on OS.
* [x] [Inline Assembly](https://github.com/grassator/mass/issues/8) Linux has stable sys call interface which we can use, but that requires some form of inline assembly support
* [x] Support for loading dynamic libraries
* [x] System V Calling Convention (struct unpacking)

**Comment by grassator** [comment]
Linux is supported for JIT, ELF support is tracked separately in https://github.com/grassator/mass/issues/44
