### ISSUE TITLE
User land negate (unary minus) implementation

### ISSUE THREAD

**Issue by grassator** [grassator/mass#31]
Things that are absolutely required for implementing an operator like unary minus in user land:

- [x] Funciton-like macro
- [x] Inline machine code bytes
- [x] Bitwise AND operator for encoding MOD R/M (ecfab42588aecf3e22db93d8768353ba4ace121d)
- [x] Bitwise shift left for encoding MOD R/M (ecfab42588aecf3e22db93d8768353ba4ace121d)
- [x] ~Some way of matching on operand type~
- [x] Named return values (6a89995c2c5fa732e43fcf29c805e2591da68205)
- [x] ~Matching on operand type for return values?~
- [ ] A way to acquire a temp register of the right size
- [x] Reflect a value into an operand variant
- [x] A way to define a new operator (aa4d0abb27e258fef6c1d5ad2663aeb9930baae6)

There are also a bunch of things that are nice to have 

- [x] Binary Integer Literals
- [x] Bitwise OR operator for encoding MOD R/M (ecfab42588aecf3e22db93d8768353ba4ace121d)
- [ ] Enums

All of it might come together into something like this:

```zig
X64_Mod :: enum({
  MOD_Displacement_0   = 0b00,
  MOD_Displacement_s8  = 0b01,
  MOD_Displacement_s32 = 0b10,
  MOD_Register         = 0b11,
});

x64_r_m32 :: (op_code: u8, reg_or_op_code : u8, r_m : Register_32) -> () {
  mod_r_m := (
    (mod << 6) +
    ((reg_or_op_code & 0b111) << 3) +
    ((r_m & 0b111))
  );
  inline_machine_code_bytes(op_code, mod_r_m);
}

negate :: macro (x : s32) -> (result : s32) {
  negate_operand(operand_variant_of(x), operand_variant_of(result))
  result
}

negate_operand :: macro (input : Register_32, result : Register_32) -> () {
  if input != result {
    x64_mov(result, input)
  }
  x64_r_m32(0xF7, 3, result)
}
```

**Comment by grassator** [comment]
Decided to go with `0 - x` implementation for now
